encyclopedia/urls.py
from django.urls import path

from . import views

app_name="encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/NewPage", views.newPage, name="NewPage"),
    path("wiki/EditPage/<str:page>", views.editPage, name="EditPage"),
    path("wiki/<str:page>", views.entryPage, name="entryPage")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
import markdown2
import random
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from . import util

class SearchForm(forms.Form):
    page = forms.CharField(label="Search Encyclopedia")

class NewPageForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'style' : 'width: 40%;'}), label="Title")
    markdown = forms.CharField(label="Mark Down Text", widget=forms.Textarea(attrs={'class' : 'form-control', 'id': 'exampleFormControlTextarea1', 'style' : 'width: 80%;'}))

class EditPageForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control', 'style' : 'width: 40%;', 'readonly': True}), label="Title")
    markdown = forms.CharField(label="Mark Down Text", widget=forms.Textarea(attrs={'class' : 'form-control', 'id': 'exampleFormControlTextarea1', 'style' : 'width: 80%;'}))

def methodPost(request):
    form = SearchForm(request.POST)
    if form.is_valid():
        page = form.cleaned_data["page"]
        return HttpResponseRedirect(f"/wiki/{page}")
    return None

def index(request):
    # Add code over here for the form input
    entries = util.list_entries()
    rand_page = random.choice(entries)
    if request.method == "POST":
        return methodPost(request)
    else:
        return render(request, "encyclopedia/index.html", {
            "entries": util.list_entries(),
            "form": SearchForm(),
            "random": random.choice(util.list_entries())
        })

def entryPage(request, page):
    the_page =  util.get_entry(page)

    if request.method == "POST":
        if 'edit' in request.POST:
            return HttpResponseRedirect(f"/wiki/EditPage/{page}")
        else:
            return methodPost(request)
    if the_page == None:
        partial_entries = []
        for p in util.list_entries():
            if page.lower() in p.lower():
                partial_entries.append(p)
        return render(request, "encyclopedia/error.html",{
            "entries": partial_entries,
            "name": page,
            "form": SearchForm(),
            "random": random.choice(util.list_entries())
        })

    the_page = markdown2.markdown(the_page)
    return render(request, "encyclopedia/page.html",{
        "name": page,
        "page": the_page,
        "form": SearchForm(),
        "random": random.choice(util.list_entries())
    })

def newPage(request):
    if request.method == "POST":
        if 'search' in request.POST:
            return methodPost(request)
        form = NewPageForm(request.POST)
        if form.is_valid():
            entries = util.list_entries()
            if form.cleaned_data["title"] in entries:
                return render(request, "encyclopedia/NewPage.html",{
                    "error": True,
                    "form": SearchForm(),
                    "newpage": NewPageForm(request.POST),
                    "random": random.choice(util.list_entries())
                })
            util.save_entry(form.cleaned_data["title"], form.cleaned_data["markdown"])
            page = form.cleaned_data["title"]
            return HttpResponseRedirect(f"/wiki/{page}")
    else: 
        return render(request, "encyclopedia/NewPage.html",{
            "form": SearchForm(),
            "newpage": NewPageForm(),
            "random": random.choice(util.list_entries())
        })

def editPage(request, page):
    if request.POST:
        if 'search' in request.POST:
            return methodPost(request)
        form = EditPageForm(request.POST)
        if form.is_valid():
            util.save_entry(form.cleaned_data["title"], form.cleaned_data["markdown"])
            page = form.cleaned_data["title"]
            return HttpResponseRedirect(f"/wiki/{page}")
    else:
        edit = EditPageForm(initial={'title': page, 'markdown': util.get_entry(page)})
        return render(request, "encyclopedia/editpage.html", {
            "form": SearchForm(),
            "editpage": edit,
            "random": random.choice(util.list_entries())
        })

encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <div class="form-group">
        <form method="post">
            {% csrf_token %}
            {{ editpage }}
            <input type="submit" title="Save">
        </form>
    </div>
    
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1> {{ name }} </h1>
    <div class="alert alert-danger" role="alert" style="width: 90%;">
        Requested page was not found
    </div>

    {% if entries %}
        <h1>Similar Pages</h1>
    {% endif %}
    <ul>
        {% for entry in entries %}
            <li>
                <a href="\wiki\{{ entry }}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
                <a href="\wiki\{{ entry }}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" name="search">
                    <!-- <input class="search" type="text" name="q" placeholder="Search Encyclopedia"> -->
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:NewPage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:entryPage' random %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>New Page</h1>
    <div class="form-group">
        {% if error %}
            <div class="alert alert-danger" role="alert" style="width: 90%;">
                This page already exists.
            </div>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            {{ newpage }}
            <input type="submit" title="Save">
        </form>
    </div>
    
{% endblock %}

encyclopedia/templates/encyclopedia/page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <div class="page">
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-primary" type="submit" name="edit" value="Edit" style="float: right; margin-right: 20px;">
        </form>
        {{ page|safe }}
    </div>

{% endblock %}